### ISSUE TITLE
Add checknum from OFX file into  CODE field of ledger entry

### ISSUE THREAD

**Issue by ratish-punnoose** [egh/ledger-autosync#103]
1. One of the transactions fields in an OFX file is CHECKNUM
2. converter.py uses ofxparse Transaction as OfxTransaction
3. The  transaction created by ofxparse has  the   .checknum field.
4. The ledger/hledger transaction format is (as per ledger documentation):
     DATE[=EDATE] [*|!] [(CODE)] DESC
     If a CODE appears in parentheses, it may be used to indicate a check number, or the type of the posting. 
  
Please, could you add the  check number that is retrieved through ofxparse to the  ledger entry output in the CODE field.

Thanks

**Comment by egh** [comment]
Thank you for the detailed report! That can be easily done.

**Comment by egh** [comment]
Added in cc6d9f6

**Comment by ratish-punnoose** [comment]
Thank you very much.
