### ISSUE TITLE
How to map transactions to accounts for Fidelity and Vanguard?

### ISSUE THREAD

**Issue by emin63** [egh/ledger-autosync#104]
Thank you for writing ledger-autosync. I am trying to get started using this to pull down my transactions from Fidelity and Vanguard but I am having some trouble as they all get merged into the same account.

It seems like the OFX download has some concept of account number. Is there a way to put in some kind of mapping so that ledger-autosync knows which items are Fidelity and which are Vanguard?

Thanks.

**Comment by egh** [comment]
Hi @emin63 - Good question! Are you using ledger-autosync to process downloaded `.ofx` files or are you connecting to fidelity & Vanguard directly via the OFX protocol?

**Comment by emin63** [comment]
OK, I think I figured some things out. I believe the main problem was not in `ledger-autosync` but that I had not setup `ofxclient` and my `~/ofxclient.ini` properly (the account descriptions I had were too generic and hence not unique).

Here is the process I used which I am documenting for reference. Feel free to correct errors or add further insights.

  1. Look in your `~/ofxclient.ini`
     - If you have setup `ofxclient` to download from multiple places, you should see multiple account sections.
  2. Find an account you want to cleanup by searching for the `number = XYZ` where `XYZ` is the account number of interest.
     - For example, I have two accounts at Fidelity (a cash management account with account number `XYZ` and a brokerage account with number `ABC`).
  3. Set the `description` field for that account in the `~/ofxclient.ini` to something descriptive.
     - For example, I set the `description` field to `Fidelity Cash Account` for my cash management account and `Fidelity Brokerage Account` for my brokerage account.
  4. Run something like
```sh
ledger-autosync -a 'Fidelity Cash Account'
  -l ldata/mainpfin.dat > ldata/fidelity/autosync-cash-acct-`date +%Y-%m-%d`.dat
```
  where you have your main ledger data file in `ldata/mainpfin.dat` and the file you want the new transactions to go into is in `ldata/fidelity/autosync-cash-acct-<date>.dat`

The above steps accomplish the following goals:
  1. You can get `Fidelity Cash Account` to appear for your cash account.
  2. If desired, you can download data for the cash account with different parameters than other accounts.

You can then do something similar for your Fidelity Brokerage Account and your Vanguard Account(s) and so on and then just run `ledger-autosync` and have it note the account descriptions more intelligently.

## Bonus Information

One other thing to be aware of is that the `--max` argument does something somewhat intuitive. It looks like `ofxclient` is designed to only download 60 transactions or 60 days of transactions. So when you increase the value of `--max`, it just starts further back in time but does not necessarily download more transactions. So if you want to get transactions from say 2020-01-01 to now, you need to run `ledger-autosync` multiple times with varying values of `--max`.

**Comment by egh** [comment]
@emin63 That all looks correct! If you filed a PR for the  README with that extra information I would be happy to merge it.

With regards to `--max`, it is a little confusing and could probably be improved. You might find that the `--resync` argument helps. Ordinarily, l-a only goes back until it sees a transaction its seen before. `--resync` overrides that, so if you have newer transactions but are missing some older ones, you can use `--max` and `--resync` to fetch those old transactions.

**Comment by emin-ec** [comment]
OK, I'm tied up with some things and still trying to resolve some questions about l-a. Once I get clarified and cleaned up on a few things, I would be happy to make a PR with some docs.

**Comment by egh** [comment]
No problem, thank you!
