### ISSUE TITLE
Need to include commissions/fees

### ISSUE THREAD

**Issue by emin63** [egh/ledger-autosync#109]
I think l-a needs to somehow include commissions/fees.

Consider OFX like below and note the fees of 0.07. I think l-a either needs to emit a record for the fees separately or use total/units instead of `UNITPRICE`. Right now it seems like l-a is just using the `UNITPRICE` and so when I look at a register report the results I get in ledger diverge from the true values because of the fees.
```xml
    <SELLSTOCK>
      <INVSELL>
	<INVTRAN>
	  <FITID>*REDACTED*
	  <DTTRADE>*REDACTED*
	  <DTSETTLE>*REDACTED*
	  <MEMO>SELL
	</INVTRAN>
	<SECID>
	  <UNIQUEID>929042109
	  <UNIQUEIDTYPE>CUSIP
	</SECID>
	<UNITS>-100.0
	<UNITPRICE>32.3944
	<FEES>0.07
	<TOTAL>3239.37
	<SUBACCTSEC>CASH
	<SUBACCTFUND>CASH
      </INVSELL>
      <SELLTYPE>SELL
    </SELLSTOCK>
```

**Comment by emin63** [comment]
FYI: see PR #110 for a proposed fix.

**Comment by egh** [comment]
Thank you for correcting this! I really appreciate it.

**Comment by emin63** [comment]
> Thank you for correcting this! I really appreciate it.

You're welcome; it was my pleasure. Btw, I just submitted PR #112 to apply a very similar fix for commissions.
