### ISSUE TITLE
Need to be able to disable guessing of offset account from payee

### ISSUE THREAD

**Issue by tesujimath** [egh/ledger-autosync#118]
Quite often I find ledger-autosync fills in the offset account incorrectly, because it is guessing based on the payee, and this may not be valid.  I have a nice set of ledger rules for allocating offset account based on regex matching, and these work.  The additional layer of guessing by ledger-autosync has caused me considerable grief when it goes wrong.

Would you be open to a PR to add a CLI option to completely disable the guessing of offset account, and just leave it as the default, e.g. Unknown?

**Comment by egh** [comment]
Hi @tesujimath - Yes, that would be absolutely welcome! I know the matching isn't great, and I'd love to improve it, but having it easily disabled seems like a great solution for when it isn't working for someone.
