### ISSUE TITLE
Chokes on long payees

### ISSUE THREAD

**Issue by bdrister** [egh/ledger-autosync#16]
```
While parsing value expression:
  (real)&((payee =~ /...256 characters of stuff... ...10 more chars/))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Invalid char ' ' (wanted '/')
ERROR:root:Error checking --real payee for ...256 characters of stuff... ...10 more chars
```

I originally came to file this more urgently as it appeared that it was causing the program to immediately stop and only whatever partial output had been flushed at that point survived, but as I was doing a final repro on this I found myself unable to reproduce that part of it. Hmm. If I see that again, I'll let you know, but for now this seems to be simply a logged error that's not blocking functionality.

**Comment by egh** [comment]
Can you send me the payee that is a problem? It might be a quoting issue rather than a length issue. Thanks!

**Comment by bdrister** [comment]
Anonymized to just indicate letters/numbers/other, they're of the form:

XXX XXXX XX 000000 XXXXXXXXXX:XXXXXXXX, XXX. XX/000000000000 XXXXXX XXXXXXX, XXXX XXXX 0 XXX XXXX XXXXX, 00XX XXXXX XXX XXXX XX 000000000 XXXXXXXX, X.X. XXX:000000000 XXXXXXXXXXX:XXXXXXXX XXXXXX XX/0000000000 000 XXXXX XXX XX X XXXXXXXXXX XX 000000000

**Comment by bdrister** [comment]
Correction; I'd just grabbed a similar payee, but it seems like they're not all exactly identical. One grabbed directly from the error message is:

XXX XXXX XX 000000 XXXXXXXXXX:XXXXXXXX, XXX. XXXXXXXXX XXXXXX XX\/000000000000 XXXXXX XXXXXXX, XXXX XXX 0 XXX XXXX XXXXX, XXXXX 00 XXX XXXX XX 000000000 XXXXXXXX, X.X. XXX:000000000 XXXXXXXXXXX:XXXXXXXX XXXXXX XX\/0000000000 000 XXXXX XXX XX X XXXXXXXXXX XX 000000000

**Comment by bdrister** [comment]
(That includes the escaping of the slashes, incidentally, since it's from the error message. The original payee doesn't have those."

**Comment by egh** [comment]
Thanks for this! Should be fixed now (in master, not yet released).
