### ISSUE TITLE
Sync does not track splits

### ISSUE THREAD

**Issue by rnapier** [egh/ledger-autosync#33]
When a previous transaction was split into multiple accounts (paycheck is a good example), the system seems to match the payee and assign it all to the last entry, even if the values are identical. It should bring forward the split if it can match the amount, and leave it in default if it cannot.

**Comment by egh** [comment]
@rnapier I'm sorry, I don't entirely understand the issue. Could you provide a sample ledger file and the behavior you would expect to see? I know that the existing account matching is not very good, but I'm not sure what you are looking for.
