### ISSUE TITLE
Exception when not all transactions have settleDate

### ISSUE THREAD

**Issue by Rudd-O** [egh/ledger-autosync#4]
[user@machine ~]$ ledger-autosync 
Caught exception processing Assets:(myaccount)Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ledgerautosync/cli.py", line 55, in sync
    (ofx, txns) = sync.get_new_txns(acct, resync=resync, max_days=max_days)
  File "/usr/lib/python2.7/site-packages/ledgerautosync/sync.py", line 70, in get_new_txns
    new_txns = self.filter(ofx)
  File "/usr/lib/python2.7/site-packages/ledgerautosync/sync.py", line 40, in filter
    sorted_txns = sorted(txns, key=lambda t: t.settleDate)
TypeError: can't compare datetime.datetime to NoneType

That's not working well there.  I can't get started.

**Comment by Rudd-O** [comment]
Dump of one transaction.  Note that date, settleDate and tradeDate are not guaranteed to exist for all transactions during that codepath.

<InvestmentTransaction type=4, units=-19.0000>
       BuyMF 0
       BuyStock 3
       Reinvest 2
       SellMF 1
       SellStock 4
       Unknown -1
       __class__ <class 'ofxparse.ofxparse.InvestmentTransaction'>
       __delattr__ <method-wrapper '__delattr__' of InvestmentTransaction object at 0x7f53c3110310>
       __dict__ {'settleDate': None, 'tradeDate': datetime.datetime(2015, 6, 15, 12, 0), 'memo': u'PIEDPIPER INC', 'unit_price': Decimal('52.0000'), 'units': Decimal('-19.0000'), 'security': u'38259P706', 'type': 4, 'id': u'965324432015061512000020150615093019705256105408'}
       __doc__ None
       __format__ <built-in method __format__ of InvestmentTransaction object at 0x7f53c3110310>
       __getattribute__ <method-wrapper '__getattribute__' of InvestmentTransaction object at 0x7f53c3110310>
       __hash__ <method-wrapper '__hash__' of InvestmentTransaction object at 0x7f53c3110310>
       __init__ <bound method InvestmentTransaction.__init__ of <InvestmentTransaction type=4, units=-19.0000>>
       __module__ ofxparse.ofxparse
       __new__ <built-in method __new__ of type object at 0x7f53d4adc0c0>
       __reduce__ <built-in method __reduce__ of InvestmentTransaction object at 0x7f53c3110310>
       __reduce_ex__ <built-in method __reduce_ex__ of InvestmentTransaction object at 0x7f53c3110310>
       __repr__ <bound method InvestmentTransaction.__repr__ of <InvestmentTransaction type=4, units=-19.0000>>
       __setattr__ <method-wrapper '__setattr__' of InvestmentTransaction object at 0x7f53c3110310>
       __sizeof__ <built-in method __sizeof__ of InvestmentTransaction object at 0x7f53c3110310>
       __str__ <method-wrapper '__str__' of InvestmentTransaction object at 0x7f53c3110310>
       __subclasshook__ <built-in method __subclasshook__ of type object at 0x172b7d0>
       __weakref__ None
       id 965324432015061512000020150615093019705256105408
       memo PIEDPIPER INC
       security 38259P706
       settleDate None
       tradeDate 2015-06-15 12:00:00
       type 4
       unit_price 52.0000
       units -19.0000
       x 4

**Comment by Rudd-O** [comment]
This code runs fine:

```python
    def filter(self, ofx):
        txns = ofx.account.statement.transactions
        if len(txns) == 0:
            sorted_txns = txns
        elif all(hasattr(txn, 'settleDate') and txn.settleDate is not None for txn in txns):
            sorted_txns = sorted(txns, key=lambda t: t.settleDate)
        elif all(hasattr(txn, 'tradeDate') and txn.tradeDate is not None for txn in txns):
            sorted_txns = sorted(txns, key=lambda t: t.tradeDate)
        else:
            sorted_txns = sorted(txns, key=lambda t: t.date)
       	acctid = ofx.account.account_id
        return [ txn for txn in sorted_txns if not(self.is_txn_synced(acctid, txn)) ]
```

**Comment by egh** [comment]
Thanks, that looks a lot like the change I made before. Maybe the best idiom is `getattr(txn, 'settleDate', None) != None`. Maybe we can replace every reference to `tradeDate` & `settleDate` with that.

**Comment by Rudd-O** [comment]
Whatever works for you :-)

**Comment by egh** [comment]
Should be fixed in https://github.com/egh/ledger-autosync/commit/fcb218fd85f31cc715c6062f977cf5b3822fa39a

**Comment by egh** [comment]
Thanks for the report!
