### ISSUE TITLE
Text encoding issues

### ISSUE THREAD

**Issue by emilecantin** [egh/ledger-autosync#43]
My bank gives me OFX / QFX files encoded as `latin1`, with the following lines in the header:
```
ENCODING:USASCII
CHARSET:8859-1
```

When I try to use them, I get the following error:
```
LookupError: unknown encoding: cp8859-1
```

I managed to make it work by changing `CHARSET` to `819`, and transactions print fine to STDOUT, but whenever I try to output it in a file (e.g `ledger-autosync --account Assets:Checking releve.qfx >> main.ledger`), I get the following error:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 32: ordinal not in range(128)
```
I do have some accented letters in my transaction descriptions, as my main language is French. It looks like ledger-autosync has a hard time with text encodings.

**Comment by egh** [comment]
Hi @emilecantin, sorry I didn't respond earlier. It's possible that the recent upgrade to python3 might help with this, or an update to ofxparse (the library we use to parse ofx files). It's unlikely this is a problem with ledger-autosync itself. However if you can provide a sanitized ofx file that triggers this error I can look into the issue.

Thank you for the report!

**Comment by NicolasPetton** [comment]
I can confirm the issue with the latest release.

Try to put any non-ascii character in a transaction text to reproduce the issue.

**Comment by llacroix** [comment]
Hi just for your information, the issue is in ofxparse, it convert the charset to "cp%s" % charset
but in the case of latin-1 it should be "iso-%s".

**Comment by egh** [comment]
@llacroix Excellent, thank you!

**Comment by Sim175** [comment]
On top of the ofxparse fix by @llacroix, I needed to force opening the file in binary mode in Python 3, otherwise my latin-1 file would fail to decode.
