### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by tbm** [egh/ledger-autosync#49]
I noticed ledger-autosync doesn't work with Python 3.  Since Python 2 will be EOL in 2020, any plans to support Python 3?

**Comment by egh** [comment]
Absolutely! It's at the top of my todo list for ledger-autosync. The last time I checked (a few years ago) some of the ofx* libraries did not support python 3, but as far as I know everything does now.

**Comment by egh** [comment]
Python 3 tests are passing in https://github.com/egh/ledger-autosync/tree/python3

I'm going to use this for myself for a little while before merging into master, but everything looks good from here.

**Comment by tbm** [comment]
That was fast, thank you!
