### ISSUE TITLE
GPL or LGPL?

### ISSUE THREAD

**Issue by eamsden** [egh/ledger-autosync#60]
The `LICENSE` file and the `license` field of `setup.py`
https://github.com/egh/ledger-autosync/blob/d2c0e403b5a5cc8f312a0401210124eaf40a887b/setup.py#L21
both specify the license as GPLv3, however the license field of classifiers specifies the LGPLv3: https://github.com/egh/ledger-autosync/blob/6923f26c7cfec5070b3ef16fdf949cba5616a78b/setup.py#L26.

A minor issue, but an issue for those of us trying to package ledger-autosync (for NixOS, in my case: https://github.com/NixOS/nixpkgs/pull/53261#discussion_r245475693)

**Comment by egh** [comment]
@eamsden Sorry, that was a copy-paste error which I have fixed. The license is GPLv3 or later.  Thank you for packaging!!
