### ISSUE TITLE
How to contribute patches

### ISSUE THREAD

**Issue by qypea** [egh/ledger-autosync#76]
What is the proper way to contribute patches to this project? A `CONTRIBUTING` file or section in the Readme would help new people jump in quicker, with less concern that they're stepping on someone else's work

**Comment by egh** [comment]
What do you have in mind? In general I am open to pull requests and don't have much of an idea of, e.g. further direction in ledger-autosync. But I'd be happy to just add a `CONTRIBUTING` file that said that.

**Comment by qypea** [comment]
A `CONTRIBUTING` file stating you were open to pull requests for bug fixes and enhancements would go a long way to help new people jump in quicker. Might be good to write down any kinds of pull requests you are not open to as well(Large refactorings, rename all X to Y, etc)

**Comment by egh** [comment]
https://github.com/egh/ledger-autosync/pull/83

**Comment by qypea** [comment]
Great. Thanks
