### ISSUE TITLE
Help with csv

### ISSUE THREAD

**Issue by edkedk99** [egh/ledger-autosync#94]
Please let me know if this is not the right place for this question.

I would like to import a csv file using ledger-autosync, but I am having trouble to adjust my file to the accepted formats. Could someone post an example csv file that can be imported so I can use as a base to generate my csv? I am not able to create a plugin, so I would like to follow an existing format.

**Comment by egh** [comment]
@edkedk99 If you look in https://github.com/egh/ledger-autosync/blob/master/fixtures` you'll see some CSV files that should work.

**Comment by edkedk99** [comment]
Thank very much. That's exactly what I needed. I don't know how I missed that folder in my seach.

**Comment by egh** [comment]
Glad that works for you @edkedk99 !
